import {
  type AppKitNetwork,
  mainnet,
  optimism,
  rootstock,
  gnosis,
  fuse,
  polygon,
  zksync,
  metis,
  polygonZkEvm,
  mantle,
  base,
  immutableZkEvm,
  mode,
  arbitrum,
  celo,
  blast,
  scroll,
  aurora,
  worldchain,
  linea,
  taiko,
  ink,
  berachain,
  lisk,
} from "@reown/appkit/networks";

export const networks = [
  mainnet,
  optimism,
  rootstock,
  gnosis,
  fuse,
  polygon,
  zksync,
  metis,
  polygonZkEvm,
  mantle,
  base,
  immutableZkEvm,
  mode,
  arbitrum,
  celo,
  blast,
  scroll,
  aurora,
  worldchain,
  linea,
  taiko,
  ink,
  berachain,
  lisk,
] as [AppKitNetwork, ...AppKitNetwork[]];

export const explorerUrls = {
  [mainnet.id]: ["https://eth.blockscout.com/"],
  [optimism.id]: ["https://optimism.blockscout.com/"],
  [rootstock.id]: ["https://rootstock.blockscout.com/"],
  [gnosis.id]: ["https://gnosis.blockscout.com/"],
  [fuse.id]: ["https://explorer.fuse.io/"],
  [polygon.id]: ["https://polygon.blockscout.com/"],
  [zksync.id]: ["https://zksync.blockscout.com/"],
  [metis.id]: ["https://andromeda-explorer.metis.io/"],
  [polygonZkEvm.id]: ["https://zkevm.blockscout.com/"],
  [mantle.id]: ["https://explorer.mantle.xyz/"],
  [base.id]: ["https://base.blockscout.com/"],
  [immutableZkEvm.id]: ["https://explorer.immutable.com/"],
  [mode.id]: ["https://explorer.mode.network/"],
  [arbitrum.id]: ["https://arbitrum.blockscout.com/"],
  [celo.id]: ["https://explorer.celo.org/mainnet/"],
  [blast.id]: ["https://blast.blockscout.com/"],
  [scroll.id]: ["https://scroll.blockscout.com/"],
  [aurora.id]: ["https://explorer.mainnet.aurora.dev/"],
  [worldchain.id]: ["https://worldchain-mainnet.explorer.alchemy.com/"],
  [linea.id]: ["https://explorer.linea.build/"],
  [taiko.id]: ["https://blockscout.mainnet.taiko.xyz/"],
  [ink.id]: ["https://explorer.inkonchain.com/"],
  [berachain.id]: ["https://bera.blockscout.com/"],
  [lisk.id]: ["https://blockscout.lisk.com/"],
};
